name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup
      run: brew install ragel boost multimarkdown ninja capnp google-sparsehash
    - name: Configure
      run: ./configure && ninja Frameworks/encoding/src/frequencies.capnp.h
    - name: Build
      run: ninja TextMate
